name: 'resnet e2e test'
on: 
  pull_request:
    types: [review_requested]
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      of_branch_or_commit:
        description: "oneflow branch or commit"
        required: true
        default: 'master'

jobs:
  build: 
    name: 'Build and test this repo'
    runs-on: ubuntu-latest
    steps:
      - run: echo "oneflow branch or commit is: ${{ github.event.inputs.of_branch_or_commit }}."
