name: ResNet50 Debug
on: 
  workflow_dispatch:
    inputs:
      of_bad_commit:
        description: 'oneflow bad commit'
        required: true
        default: 'HEAD'
      of_good_commit:
        description: 'oneflow good commit'
        required: true
      module_resnet_type:
        description: 'ResNet50 type, eg:ddp,graph'
        required: true
        default: 'graph'
      gpu_num_per_node:
        description: 'gpu number per node'
        required: true
        default: 1
env:
  DEBUG_WORKSPACE: debug_workspace

jobs:
  test_module:
    name: Test Module ResNet50
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Oneflow-Inc/OneFlow-Benchmark
        uses: actions/checkout@v2
        with:
          path: debug_workspace/OneFlow-Benchmark
          ref: v0.5.0_many_gpu_test
      - name: Checkout Oneflow-Inc/oneflow
        uses: actions/checkout@v2
        with:
          repository: Oneflow-Inc/oneflow
          path: debug_workspace/oneflow
          ref: master
      - name: Build OneFlow
        env:
          module_resnet_type: ${{ github.event.inputs.of_good_commit }}
        run: |
          git --version
          cd debug_workspace/oneflow
          pwd
          ls
          git bisect start ${{ github.event.inputs.of_bad_commit }} ${{ github.event.inputs.of_good_commit }}
          echo "--------------"
          git bisect log
          git bisect good
          git bisect log
          git bisect good
          git log --pretty=format:"%H-%cd-%cr" -2
          git status
          git bisect reset


          
